server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: demo-server #服务调用name
  datasource:
    url: jdbc:mysql://rm-bp14nmd1q0bg5iw0xvo.mysql.rds.aliyuncs.com:3306/oa?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&useAffectedRows=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 5%-yLhEbty
    type: com.alibaba.druid.pool.DruidDataSource
  aop:
    proxy-target-class: true
  # Redis数据库索引（默认为0）  
  redis:
    database: 1
    host: 47.96.68.24
    port: 6379
    password: 0ks9jz7x
    timeout: 5000
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 10  # 最大活跃链接数 默认8
        max-idle: 10  # 最大空闲连接数 默认8
        min-idle: 0 # 最小空闲连接数 默认0
        max-wait: 1000  # 连接池最大阻塞等待时间（使用负值表示没有限制）

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 'null' # 逻辑已删除值(默认为 1)，null字符串mybatis-plus会转换为null处理
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml